---
title: "Sugerencia correcciones_01-Prólogo"
output: html_document
---

# Presentación

Las ciencias regionales de ser una disciplina menor, una suerte de espacio para la experimentación de teorías y métodos que no tenían cabida en las corrientes principales de _ciencias_ plenamente constituidas _, _ se han ido abriendo paso y consolidando. Las ciencias regionales han ido adquiriendo “una amplia orientación multidisciplinaria sobre temas regionales y urbanos, combinando y siendo un complemento a la economía regional, geografía social y económica, economía urbana, ciencia del transporte, ciencia ambiental, ciencia política y teoría de la planificación” (@FischerNijkamp2014). La realidad es que en los pasados 50 años las ciencias regionales han _evolucionado_ como un campo de investigación en pleno derecho, _esto_ tras un largo recorrido desde los inicios de la economía como ciencia, _comenzando_ con los trabajos de Adam Smith que trataban algunos elementos relacionados con la localización de actividades comerciales, pasando por los _estudios_ clásicos de Von Thünen, A. Weber, A. Lösch _(_ todos ellos relacionados con la denominada teoría de la localización _)_, hasta _llegar a_ la consolidación de las ciencias regionales como disciplina gracias al impulso de Walter Isaard que trata de brindar una perspectiva teórica y metodológica coherente con un fuerte soporte empírico desde una perspectiva multidisciplinaria. Las contribuciones de W. Isaard abarcan una multitud de campos tales como la ecología, el estudio de los transportes e incluso el manejo de conflictos.

Si bien entonces las ciencias regionales abarcan múltiples líneas temáticas, hay dos de ellas que se constituyen en _tópicos_ clásicos y son lo que podría ser denominado "la corriente principal de las ciencias regionales": el estudio de las fuerzas de aglomeración y los determinantes de la localización de la actividad. Buena parte de las investigaciones de estos ejes buscan responder a preguntas como _; _ ¿Por qué las actividades económicas no se distribuyen de forma homogénea en el espacio? y ¿Qué hace que determinadas actividades se localicen en unos sitios y no en otros?

En su *Handbook of Regional Science*, Manfred Fischer y Peter Nijkamp señalan que quizá sean dos los elementos clave que constituyen a la ciencia regional: un enfoque multidisciplinario y un fuerte análisis cuantitativo. Respecto al primer elemento, si bien es cierto que la economía espacial, urbana y regional, han _representado_ pasos alentadores hacia la aproximación del economista con otros científicos sociales, no _se suele _ mirar con la frecuencia que exigen las problemáticas sociales hacia otros campos _de estudio_ para construir _vínculos comunicadores_ que permitan un efectivo trabajo multidisciplinario. Por _ello_, aún sigue siendo necesario construir alternativas de formación en el núcleo terminal para los estudiantes de licenciatura que busquen romper la endogamia de la profesión . Esto es en alguna medida lo que en el Área de Concentración de Economía de la Innovación: empresas, redes y territorio, _la cual forma parte del Departamento de Economía_ en la Universidad Autónoma Metropolitana Unidad Azcapotzalco, se ha buscado impulsar. 

En tanto, sobre el enfoque cuantitativo que caracteriza a las ciencias regionales, es cierto que en todos los planes de estudio de economía encontramos un sólido repertorio de instrumentos de carácter cuantitativo: matemáticas, estadística y, por supuesto, econometría. No obstante, las herramientas requeridas para el análisis de la realidad desde una perspectiva espacial siguen siendo escasas dentro de la formación a nivel de licenciatura. Estas notas buscan ser una contribución, por pequeña o grande que esta sea, para subsanar dicha situación. _Este trabajo_ está, por tanto, fundamentalmente dirigido a los estudiantes de licenciatura interesados en el desarrollo de habilidades técnicas para el análisis cuantitativo que exigen las ciencias regionales y el enfoque espacial de la economía. Así pues, el objetivo de estas notas es guiar al estudiante, desde un enfoque fundamentalmente práctico, en el conocimiento y manejo de técnicas para la exploración, análisis y modelado de información espacial mediante el uso de **R** y **RStudio**, un programa informático y lenguaje de programación enfocado en el análisis estadístico y visualización de información y entorno de desarrollo integrado, respectivamente.

En el capítulo 1, se presentan los elementos básicos de **R** y **RStudio** a través de la utilización del enfoque del análisis exploratorio de datos. En el capítulo 2, se presentan múltiples medidas clásicas para el análisis regional, tales como coeficientes de concentración, diversificación y especialización de diferente naturaleza. En el capítulo 3 se muestra cómo elaborar diversos tipos de mapas coropléticos y la enorme flexibilidad de personalización de estilos que tiene **R** para tal efecto. En el capítulo 4 se presenta un repaso muy sintético a los modelos de regresión simple _enfatizando_ el problema de la autocorrelación que se puede presentar cuando se estima un modelo lineal con datos espaciales para, a partir de lo anterior, mostrar algunas de las diferentes alternativas de modelación econométrica espacial _disponibles_ en R.

Es necesario mencionar que estas notas no son más que un esfuerzo de recopilación y sistematización de la infinidad de materiales que la activa comunidad de **R**, interesada en el análisis espacial en México y el mundo, sube y actualiza desinteresadamente todos los días en la red. Así debería ser siempre el conocimiento: libre y abierto como el software que es usado aquí. Así pues, si algún mérito puede tener este material es justamente su sentido didáctico y de compilación ordenada de materiales existentes, echando mano de bases de datos que refieran la realidad económica regional mexicana.







## Referencias

[@FischerNijkamp2014]
